name: "tests"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:
  schedule:
    - cron: '30 23 * * *'

jobs:
  test-linux:
    name: Playwright@${{ matrix.playwright}} ${{ matrix.os }} headless=${{ matrix.headless }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]
        playwright: [1.12.0]
        headless: [true, false]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install operating system dependencies
      run: npx playwright install-deps
    - uses: actions/checkout@v2
    - uses: microsoft/playwright-github-action@v1.5.0
    - name: Install Media Pack
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: Install-WindowsFeature Server-Media-Foundation
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    #- name: Download drivers
      #shell: bash
      #run: scripts/download_driver_for_all_platforms.sh
    - name: Build with Maven
      run: mvn -B package -D skipTests --no-transfer-progress
    - name: Run tests
      run: mvn test --no-transfer-progress
      env:
        BROWSER: chromium
        BROWSER_CHANNEL: ${{ matrix.browser-channel }}
    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: build/allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history

